[project]
name = "dummy-svp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "ipdb>=0.13.13",
    "ipython>=8.31.0",
    "music21>=9.3.0",
    "pydantic>=2.10.5",
    "pytest>=8.3.4",
]
